const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 1.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      _id: "2",
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/d2.jpg",
      price: 220,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.3,
      numReviews: 16,
      description: "high quality products",
    },
    {
      _id: "3",
      name: "Lacoste free shirt",
      category: "Shirts",
      image: "/images/d3.jpg",
      price: 330,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 12,
      description: "high quality products",
    },
    {
      _id: "4",
      name: "Puma Sling Pants",
      category: "Pants",
      image: "/images/p1.jpg",
      price: 150,
      countInStock: 12,
      brand: "Puma",
      rating: 4.1,
      numReviews: 11,
      description: "high quality products",
    },
    {
      _id: "5",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p2.jpg",
      price: 140,
      countInStock: 20,
      brand: "Nike",
      rating: 4.4,
      numReviews: 12,
      description: "high quality products",
    },
    {
      _id: "6",
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 130,
      countInStock: 5,
      brand: "Adidas",
      rating: 4.9,
      numReviews: 30,
      description: "high quality products",
    },
  ],
};

export default data;
